In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import f1_score
from scipy.special import logit, expit
import pickle

In [23]:
oof = pd.read_csv('../preds/oof_pred.csv')

In [24]:
oof.head()

Id   Target  fold    pred_0    pred_1  \
0  00070df0-bbc3-11e8-b2bc-ac1f6b6435d0     16 0     2  0.940042  0.019254   
1  000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  7 1 2 0     1  0.820848  0.999116   
2  000a9596-bbc4-11e8-b2bc-ac1f6b6435d0        5     2  0.920208  0.020876   
3  000c99ba-bba4-11e8-b2b9-ac1f6b6435d0        1     2  0.612504  0.924049   
4  001838f8-bbca-11e8-b2bc-ac1f6b6435d0       18     4  0.252602  0.001148   

     pred_2    pred_3    pred_4    pred_5    pred_6      ...        pred_18  \
0  0.351159  0.006079  0.015875  0.145716  0.002299      ...       0.423793   
1  0.525593  0.045257  0.000969  0.047155  0.023687      ...       0.005552   
2  0.622096  0.165277  0.058788  0.969752  0.011474      ...       0.048177   
3  0.119747  0.012099  0.038203  0.005261  0.968421      ...       0.005491   
4  0.022260  0.003731  0.001436  0.018437  0.002753      ...       0.994571   

    pred_19       pred_20   pred_21   pred_22   pred_23   pred_24   pred_25  \
0  0.155631  3.311639e-05  0.130876  0.007847  0.017331  0.000069  0.376820   
1  0.005257  5.749720e-05  0.033169  0.002660  0.010750  0.000110  0.195760   
2  0.172556  7.293192e-05  0.196732  0.162877  0.035505  0.010758  0.295205   
3  0.018319  1.812955e-04  0.556480  0.061768  0.017533  0.000006  0.606015   
4  0.328054  9.264447e-07  0.010853  0.002268  0.003845  0.000694  0.285621   

    pred_26       pred_27  
0  0.000992  2.412575e-05  
1  0.000041  7.956502e-07  
2  0.001464  2.621121e-05  
3  0.019924  1.735940e-05  
4  0.000002  2.986564e-08  

[5 rows x 31 columns]

In [25]:
target = oof.Target.values

In [26]:
target.shape

(31072,)

In [27]:
for i in range(target.shape[0]):
    target[i] = list(map(int, target[i].split(' ')))

In [28]:
target[i]

[2, 0]

In [10]:
target[0]

['16', '0']

In [13]:
list(map(int, target[0]))

[16, 0]

In [29]:
Target = np.zeros((target.shape[0], 28))

In [32]:
Target[0,:].shape

(28,)

In [36]:
Target[0,:][target[i]] = 1

In [37]:
Target[0,:]

array([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
for i in range(target.shape[0]):
    Target[i,:][target[i]] = 1

In [41]:
Target[:,0].shape

(31072,)

In [43]:
oof['pred_0'].values.shape

(31072,)

In [45]:
(oof['pred_0'].values > 0.84)*1

array([1, 0, 1, ..., 0, 0, 1])

In [46]:
f1_score(Target[:,0], (oof['pred_0'].values > 0.84)*1)

0.8145443244503147

In [54]:
f1_score(Target[:,0], (oof['pred_0'].values > 0.71)*1)

0.8159490075172341

In [62]:
f1_score(Target[:,1], (oof['pred_1'].values > 0.99)*1)

0.7790055248618785

In [66]:
f1_score(Target[:,8], (oof['pred_8'].values > 0.05)*1)

0.7751937984496124

In [68]:
oof66_probs = pd.read_csv('../preds/oof66_probs.csv')

In [69]:
oof66_probs.head()

id data        p0        p1        p2  \
0  00070df0-bbc3-11e8-b2bc-ac1f6b6435d0  oof  0.593788  0.375898  0.435990   
1  000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  oof  0.533248  0.612703  0.469979   
2  000a9596-bbc4-11e8-b2bc-ac1f6b6435d0  oof  0.568403  0.397393  0.488341   
3  000c99ba-bba4-11e8-b2b9-ac1f6b6435d0  oof  0.546201  0.605755  0.419404   
4  001838f8-bbca-11e8-b2bc-ac1f6b6435d0  oof  0.495074  0.371248  0.429676   

         p3        p4        p5        p6        p7    ...          p18  \
0  0.330360  0.364444  0.454987  0.321135  0.421705    ...     0.473793   
1  0.405523  0.369507  0.429742  0.382987  0.503600    ...     0.366631   
2  0.488467  0.422017  0.554570  0.377031  0.454148    ...     0.407967   
3  0.387817  0.398623  0.396394  0.453517  0.386389    ...     0.362903   
4  0.390139  0.361621  0.401643  0.360942  0.416369    ...     0.593574   

        p19       p20       p21       p22       p23       p24       p25  \
0  0.455051  0.293550  0.437272  0.361133  0.379272  0.331481  0.489557   
1  0.374946  0.344130  0.381159  0.389741  0.398122  0.360515  0.408260   
2  0.440541  0.430399  0.390864  0.415024  0.430823  0.375191  0.464016   
3  0.381222  0.279476  0.415416  0.381239  0.378134  0.303103  0.511146   
4  0.454285  0.304013  0.353871  0.384033  0.356007  0.383759  0.418303   

        p26       p27  
0  0.335664  0.287815  
1  0.374281  0.324469  
2  0.393774  0.338479  
3  0.364389  0.284949  
4  0.305295  0.306030  

[5 rows x 30 columns]

In [70]:
oof66_probs.shape

(31072, 30)

In [71]:
thresholds = np.linspace(0, 1, 101)

In [72]:
thresholds

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [76]:
oof66_probs[oof66_probs.columns[2:]].values.shape

(31072, 28)

In [78]:
[oof66_probs.columns[2:]].values > thresholds)

SyntaxError: invalid syntax (<ipython-input-78-d7bc0436e548>, line 1)

In [79]:
scores = np.array([f1_score(Target, (oof66_probs[oof66_probs.columns[2:]].values > t).astype(int), 
                            average='macro') for t in thresholds])

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [81]:
scores.shape

(101,)

In [82]:
np.argmax(scores)

53

In [83]:
np.max(scores)

0.74559786084789

In [2]:
fidx = 'ens'
midx = '66'

In [12]:
glist = ['air_u67',
           'preresnet_u67','preresnet_u101',
           'resnet_w65', 'se_resnext_u29'
           ]

In [14]:
nfold = 4

oof_dir = '../../Human_Protein_Atlas/metafeatures/oof/'

In [6]:

PATH_TO_TRAIN = '../../Human_Protein_Atlas/input/train/'
PATH_TO_TEST = '../../Human_Protein_Atlas/input/test/'
PATH_TO_TARGET = '../../Human_Protein_Atlas/input/train.csv'
PATH_TO_SUB = '../../Human_Protein_Atlas/input/sample_submission.csv'

In [7]:
sub = pd.read_csv(PATH_TO_SUB)

In [8]:
sub.head()

Id  Predicted
0  00008af0-bad0-11e8-b2b8-ac1f6b6435d0          0
1  0000a892-bacf-11e8-b2b8-ac1f6b6435d0          0
2  0006faa6-bac7-11e8-b2b7-ac1f6b6435d0          0
3  0008baca-bad7-11e8-b2b9-ac1f6b6435d0          0
4  000cce7e-bad4-11e8-b2b8-ac1f6b6435d0          0

In [9]:
df = pd.read_csv(PATH_TO_TARGET)
df.set_index('Id',inplace=True)
print(df.head())
print(df.shape)

                                       Target
Id                                           
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0     16 0
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  7 1 2 0
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0        5
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0        1
001838f8-bbca-11e8-b2bc-ac1f6b6435d0       18
(31072, 1)


In [10]:
file_list = list(df.index.values)

ss = pd.read_csv(PATH_TO_SUB)
ss.set_index('Id',inplace=True)
print(ss.head())
print(ss.shape)

                                      Predicted
Id                                             
00008af0-bad0-11e8-b2b8-ac1f6b6435d0          0
0000a892-bacf-11e8-b2b8-ac1f6b6435d0          0
0006faa6-bac7-11e8-b2b7-ac1f6b6435d0          0
0008baca-bad7-11e8-b2b9-ac1f6b6435d0          0
000cce7e-bad4-11e8-b2b8-ac1f6b6435d0          0
(11702, 1)


In [10]:
oof = df.copy()
# print(oof.head())
# print(oof.shape)
eps = 1e-6

In [15]:

oof = df.copy()
# print(oof.head())
# print(oof.shape)
eps = 1e-6

for k,m in enumerate(glist):
    # print(m),
    first = True
    for fold in range(nfold):
        idf, pooff, yooff = pickle.load(open(oof_dir+m+'_'+str(fold)+'.pkl','rb'))
        # change to probability scale
        pooff = expit(pooff)
        

        if first:
            id = idf
            poof = pooff.copy()
            yoof = yooff.copy()
            first = False
        else:
            id = id + idf
            poof = np.concatenate((poof,pooff))
            yoof = np.concatenate((yoof,yooff))
    
    mdf = pd.DataFrame({'Id':id})
    # print(poof.shape)
    if k==0: mdf['y'] = [yoof[i] for i in range(yoof.shape[0])]
    mdf[m] = [poof[i] for i in range(poof.shape[0])]
    mdf.set_index('Id',inplace=True)
    oof = oof.join(mdf)

In [16]:
oof.shape

(31072, 7)

In [17]:
oof.head()

Target  \
Id                                              
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0     16 0   
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  7 1 2 0   
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0        5   
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0        1   
001838f8-bbca-11e8-b2bc-ac1f6b6435d0       18   

                                                                                      y  \
Id                                                                                        
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  [1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...   
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...   
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
001838f8-bbca-11e8-b2bc-ac1f6b6435d0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                                                                air_u67  \
Id                                                                                        
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0  [[[0.9552974]], [[0.011893719]], [[0.02456743]...   
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  [[[0.97475284]], [[0.9937784]], [[0.37172255]]...   
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0  [[[0.9680168]], [[0.0082058655]], [[0.29154035...   
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0  [[[0.9572456]], [[0.99069935]], [[0.05033453]]...   
001838f8-bbca-11e8-b2bc-ac1f6b6435d0  [[[0.184256]], [[0.0006398597]], [[0.014315954...   

                                                                          preresnet_u67  \
Id                                                                                        
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0  [[[0.9008]], [[0.04977778]], [[0.06152666]], [...   
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  [[[0.7416709]], [[0.99948597]], [[0.072097324]...   
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0  [[[0.9560007]], [[0.0061894692]], [[0.3604504]...   
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0  [[[0.31696457]], [[0.99046564]], [[0.003620990...   
001838f8-bbca-11e8-b2bc-ac1f6b6435d0  [[[0.037844375]], [[0.00064213324]], [[0.00495...   

                                                                         preresnet_u101  \
Id                                                                                        
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0  [[[0.9928462]], [[0.0033091686]], [[0.02205755...   
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  [[[0.8883914]], [[0.99836713]], [[0.21986316]]...   
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0  [[[0.93580484]], [[0.037184846]], [[0.48354197...   
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0  [[[0.90816665]], [[0.998226]], [[0.04174795]],...   
001838f8-bbca-11e8-b2bc-ac1f6b6435d0  [[[0.6757472]], [[0.0011689868]], [[0.01058629...   

                                                                             resnet_w65  \
Id                                                                                        
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0  [[[0.9949687]], [[0.008769571]], [[0.05128505]...   
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  [[[0.9355388]], [[0.99766314]], [[0.25203508]]...   
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0  [[[0.89877224]], [[0.007357184]], [[0.47415993...   
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0  [[[0.9247875]], [[0.9722527]], [[0.03123361]],...   
001838f8-bbca-11e8-b2bc-ac1f6b6435d0  [[[0.12146013]], [[0.000605252]], [[0.04767052...   

                                                                         se_resnext_u29  
Id                                                                                       
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0  [[[0.99430543]], [[0.016006052]], [[0.02002830...  
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  [[[0.7101919]], [[0.969549]], [[0.27546024]], ...  
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0  [[[0.9792124]], [[0.017325625]], [[0.5496751]]...  
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0  [[[0.846639]], [[

In [18]:
y = np.array(oof.y.values.tolist())

In [28]:
y.shape

(31072, 28)

In [29]:
import fastai

In [30]:

ymean = np.mean(y,axis=0)
print(ymean)

[4.1468203e-01 4.0357880e-02 1.1653579e-01 5.0238155e-02 5.9796602e-02
 8.0876671e-02 3.2440782e-02 9.0821318e-02 1.7057158e-03 1.4482492e-03
 9.0113288e-04 3.5176363e-02 2.2142122e-02 1.7282441e-02 3.4307417e-02
 6.7584962e-04 1.7057158e-02 6.7584962e-03 2.9029351e-02 4.7695674e-02
 5.5355304e-03 1.2155639e-01 2.5811020e-02 9.5423535e-02 1.0363027e-02
 2.6480433e-01 1.0556128e-02 3.5401649e-04]


In [19]:
air_u67 = np.array(oof.air_u67.values.tolist())


In [20]:
air_u67 = air_u67.reshape((31072, 28))
air_u67.shape

(31072, 28)

In [41]:
air_u67[:,0]

(31072,)

In [43]:
f1_score(y[:,0], (air_u67[:,0] > 0.5)*1.)

0.7921986721144025

In [44]:
f1_score(y, (air_u67 > 0.5)*1., average='macro')

0.6209110155725419

In [23]:
thresholds =np.transpose(np.array([list(np.linspace(0.01,0.99, 99))]*28))

In [24]:
thresholds[:,0]

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [67]:
np.transpose((air_u67[:,0] > thresholds[:,0].reshape(-1,1))*1.).shape

(31072, 99)

In [60]:
np.transpose(thresholds[:,0])

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [62]:
thresholds[:,0].reshape(-1,1).shape

(99, 1)

In [69]:
f1_score(y[:,0], np.transpose((air_u67[:,0] > thresholds[:,0].reshape(-1,1))*1.)[:,0])

0.5985404852654086

In [71]:
f1_score(y, (air_u67 > 0.5)*1., average=None)

array([0.79219867, 0.76187357, 0.73427945, 0.69112174, 0.68956797,
       0.60185608, 0.4729362 , 0.72692646, 0.86725664, 0.80851064,
       0.75409836, 0.63991698, 0.54579615, 0.53081761, 0.74251939,
       0.61904762, 0.30316742, 0.35836177, 0.44329184, 0.52401353,
       0.50194553, 0.6147929 , 0.48355755, 0.72957011, 0.64879357,
       0.64723724, 0.45974576, 0.69230769])

In [72]:
air_u67.shape

(31072, 28)

In [73]:
thresholds.shape

(99, 28)

In [75]:
thresholds[:,0].reshape(-1,1).shape

(99, 1)

In [83]:
(air_u67 > thresholds)*1.

ValueError: operands could not be broadcast together with shapes (31072,28) (99,28) 

In [87]:
((air_u67 > thresholds[:,0].reshape(-1,1))*1.).shape

ValueError: operands could not be broadcast together with shapes (31072,28) (99,1) 

In [91]:
(air_u67[:,np.newaxis] + list(range(28))).shape

(31072, 1, 28)

In [97]:
np.array([list(range(28)), list(range(28))]).shape

(2, 28)

In [98]:
(air_u67[:,np.newaxis] + np.array([list(range(28)), list(range(28))])).shape

(31072, 2, 28)

In [105]:
((air_u67[:,np.newaxis] > thresholds)*1.).shape

(31072, 99, 28)

In [103]:
y.shape

(31072, 28)

In [106]:
(air_u67[:,np.newaxis] > thresholds)*1.

array([[[1., 1., 1., ..., 1., 0., 0.],
        [1., 0., 1., ..., 1., 0., 0.],
        [1., 0., 0., ..., 1., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.],
        ...,
        [1., 1., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.]],

       [[1., 0., 1., ..., 1., 0., 0.],
        [1., 0., 1., ..., 1., 0., 0.],
        [1., 0., 1., ..., 1., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[1., 1., 1., ..., 1., 0., 0.],
        [1., 0., 1., ..., 1., 0., 0.],
        [1., 0., 1., ..., 1., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [107]:
f1_score(y, (air_u67[:,np.newaxis] > thresholds)*1., average=None)

ValueError: Classification metrics can't handle a mix of multilabel-indicator and unknown targets

In [108]:
Big_Tensor = (air_u67[:,np.newaxis] > thresholds)*1.

In [109]:
Big_Tensor.shape

(31072, 99, 28)

In [111]:
Big_Tensor[:,0,:].shape

(31072, 28)

In [113]:
f1_score(y, Big_Tensor[:,0,:], average=None)

array([0.59854049, 0.14964115, 0.23815334, 0.15101146, 0.17938746,
       0.17908947, 0.09905919, 0.20166804, 0.13495277, 0.13622291,
       0.089701  , 0.10077917, 0.08483258, 0.07370699, 0.17718975,
       0.07216495, 0.05137413, 0.05466095, 0.08462597, 0.10773551,
       0.0840249 , 0.24980127, 0.07471453, 0.22382808, 0.17044168,
       0.42841883, 0.09142012, 0.02624672])

In [114]:
Final_Tensor = [f1_score(y, Big_Tensor[:,x,:], average=None) for x in range(99)]

In [115]:
Final_Tensor = np.array(Final_Tensor)

In [116]:
Final_Tensor.shape

(99, 28)

In [121]:
np.argmax(Final_Tensor, axis=0)+1

array([82, 87, 81, 84, 90, 82, 88, 84, 61, 86, 88, 86, 91, 92, 94, 71, 91,
       88, 85, 82, 96, 77, 90, 90, 71, 72, 89, 87])

In [123]:
np.max(Final_Tensor, axis=0).mean()

0.7108776996492326

In [21]:
preresnet_u67 = np.array(oof.preresnet_u67.values.tolist())
preresnet_u101 = np.array(oof.preresnet_u101.values.tolist())
preresnet_u67 = preresnet_u67.reshape((31072, 28))
preresnet_u101 = preresnet_u101.reshape((31072, 28))

In [25]:
Big_Tensor = (preresnet_u67[:,np.newaxis] > thresholds)*1.
Final_Tensor = [f1_score(y, Big_Tensor[:,x,:], average=None) for x in range(99)]
Final_Tensor = np.array(Final_Tensor)
np.max(Final_Tensor, axis=0).mean()

0.7092749679908568

In [26]:
Big_Tensor = (preresnet_u101[:,np.newaxis] > thresholds)*1.
Final_Tensor = [f1_score(y, Big_Tensor[:,x,:], average=None) for x in range(99)]
Final_Tensor = np.array(Final_Tensor)
np.max(Final_Tensor, axis=0).mean()

0.7056871990007961

In [27]:
se_resnext_u29 = np.array(oof.se_resnext_u29.values.tolist())
resnet_w65 = np.array(oof.resnet_w65.values.tolist())
se_resnext_u29 = se_resnext_u29.reshape((31072, 28))
resnet_w65 = resnet_w65.reshape((31072, 28))

In [28]:
Big_Tensor = (se_resnext_u29[:,np.newaxis] > thresholds)*1.
Final_Tensor = [f1_score(y, Big_Tensor[:,x,:], average=None) for x in range(99)]
Final_Tensor = np.array(Final_Tensor)
np.max(Final_Tensor, axis=0).mean()

0.7015426593208052

In [29]:
Big_Tensor = (resnet_w65[:,np.newaxis] > thresholds)*1.
Final_Tensor = [f1_score(y, Big_Tensor[:,x,:], average=None) for x in range(99)]
Final_Tensor = np.array(Final_Tensor)
np.max(Final_Tensor, axis=0).mean()

0.7088338470137628

In [128]:
thresholds.shape

(99, 28)

In [133]:
preresnet_u67.shape

(31072, 28)

In [106]:
threshold_0 = np.linspace(0.01, 0.99, 99)

In [135]:
threshold_0

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [149]:
np.transpose(preresnet_u67[:,0] > threshold_0.reshape(-1,1))*1.

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [166]:
f1_score((np.transpose(preresnet_u67[:,0] > threshold_0.reshape(-1,1))*1.)[:,1], y[:,0])

0.6139785715990169

In [152]:
y[:,0].shape

(31072,)

In [154]:
(np.transpose(preresnet_u67[:,0] > threshold_0.reshape(-1,1))*1.).shape

(31072, 99)

In [161]:
Big_Tensor[:,0,:].shape

(31072, 28)

In [167]:
scores = [f1_score((np.transpose(preresnet_u67[:,0] > threshold_0.reshape(-1,1))*1.)[:,k], y[:,0]) for k in range(99)]

In [168]:
np.max(scores)

0.8352763782133794

In [172]:
y[:,0]

array([1., 1., 0., ..., 0., 0., 1.], dtype=float32)

In [31]:
preresnet_u101.shape

(31072, 28)

In [32]:
oof.head()

Target  \
Id                                              
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0     16 0   
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  7 1 2 0   
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0        5   
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0        1   
001838f8-bbca-11e8-b2bc-ac1f6b6435d0       18   

                                                                                      y  \
Id                                                                                        
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  [1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...   
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...   
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
001838f8-bbca-11e8-b2bc-ac1f6b6435d0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                                                                air_u67  \
Id                                                                                        
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0  [[[0.9552974]], [[0.011893719]], [[0.02456743]...   
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  [[[0.97475284]], [[0.9937784]], [[0.37172255]]...   
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0  [[[0.9680168]], [[0.0082058655]], [[0.29154035...   
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0  [[[0.9572456]], [[0.99069935]], [[0.05033453]]...   
001838f8-bbca-11e8-b2bc-ac1f6b6435d0  [[[0.184256]], [[0.0006398597]], [[0.014315954...   

                                                                          preresnet_u67  \
Id                                                                                        
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0  [[[0.9008]], [[0.04977778]], [[0.06152666]], [...   
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  [[[0.7416709]], [[0.99948597]], [[0.072097324]...   
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0  [[[0.9560007]], [[0.0061894692]], [[0.3604504]...   
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0  [[[0.31696457]], [[0.99046564]], [[0.003620990...   
001838f8-bbca-11e8-b2bc-ac1f6b6435d0  [[[0.037844375]], [[0.00064213324]], [[0.00495...   

                                                                         preresnet_u101  \
Id                                                                                        
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0  [[[0.9928462]], [[0.0033091686]], [[0.02205755...   
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  [[[0.8883914]], [[0.99836713]], [[0.21986316]]...   
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0  [[[0.93580484]], [[0.037184846]], [[0.48354197...   
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0  [[[0.90816665]], [[0.998226]], [[0.04174795]],...   
001838f8-bbca-11e8-b2bc-ac1f6b6435d0  [[[0.6757472]], [[0.0011689868]], [[0.01058629...   

                                                                             resnet_w65  \
Id                                                                                        
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0  [[[0.9949687]], [[0.008769571]], [[0.05128505]...   
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  [[[0.9355388]], [[0.99766314]], [[0.25203508]]...   
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0  [[[0.89877224]], [[0.007357184]], [[0.47415993...   
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0  [[[0.9247875]], [[0.9722527]], [[0.03123361]],...   
001838f8-bbca-11e8-b2bc-ac1f6b6435d0  [[[0.12146013]], [[0.000605252]], [[0.04767052...   

                                                                         se_resnext_u29  
Id                                                                                       
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0  [[[0.99430543]], [[0.016006052]], [[0.02002830...  
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  [[[0.7101919]], [[0.969549]], [[0.27546024]], ...  
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0  [[[0.9792124]], [[0.017325625]], [[0.5496751]]...  
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0  [[[0.846639]], [[

In [33]:
train_five = np.hstack((air_u67, preresnet_u67, preresnet_u101, resnet_w65, se_resnext_u29))

In [34]:
train_five.shape

(31072, 140)

In [35]:
cluster4x_folds = pd.read_csv('../Russ/cluster4x_folds.csv')

In [36]:
cluster4x_folds.head()

Id  cluster4
0  00070df0-bbc3-11e8-b2bc-ac1f6b6435d0         0
1  000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0         1
2  000a9596-bbc4-11e8-b2bc-ac1f6b6435d0         1
3  000c99ba-bba4-11e8-b2b9-ac1f6b6435d0         0
4  001838f8-bbca-11e8-b2bc-ac1f6b6435d0         3

In [38]:
np.unique(cluster4x_folds.cluster4.values, return_counts=True)

(array([0, 1, 2, 3]), array([ 9970, 15381, 13030, 18620]))

In [47]:
np.where(cluster4x_folds.cluster4.values == 0)[0].shape

(47031,)

In [46]:
y[:,0].shape

(31072,)

In [48]:
y[:,0][np.where(cluster4x_folds.cluster4.values == 0)[0]]

IndexError: index 31073 is out of bounds for axis 1 with size 31072

In [49]:
cluster4x_folds.shape

(57001, 2)

In [50]:
sub.shape

(11702, 2)

In [51]:
df.head()

Target
Id                                           
00070df0-bbc3-11e8-b2bc-ac1f6b6435d0     16 0
000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  7 1 2 0
000a9596-bbc4-11e8-b2bc-ac1f6b6435d0        5
000c99ba-bba4-11e8-b2b9-ac1f6b6435d0        1
001838f8-bbca-11e8-b2bc-ac1f6b6435d0       18

In [52]:
df_folds = df.merge(cluster4x_folds, on='Id')

In [53]:
df_folds.shape

(31072, 3)

In [54]:
df_folds.head()

Id   Target  cluster4
0  00070df0-bbc3-11e8-b2bc-ac1f6b6435d0     16 0         0
1  000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  7 1 2 0         1
2  000a9596-bbc4-11e8-b2bc-ac1f6b6435d0        5         1
3  000c99ba-bba4-11e8-b2b9-ac1f6b6435d0        1         0
4  001838f8-bbca-11e8-b2bc-ac1f6b6435d0       18         3

In [55]:
oof_folds = oof.merge(cluster4x_folds, on='Id')

In [56]:
oof_folds.head()

Id   Target  \
0  00070df0-bbc3-11e8-b2bc-ac1f6b6435d0     16 0   
1  000a6c98-bb9b-11e8-b2b9-ac1f6b6435d0  7 1 2 0   
2  000a9596-bbc4-11e8-b2bc-ac1f6b6435d0        5   
3  000c99ba-bba4-11e8-b2b9-ac1f6b6435d0        1   
4  001838f8-bbca-11e8-b2bc-ac1f6b6435d0       18   

                                                   y  \
0  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                             air_u67  \
0  [[[0.9552974]], [[0.011893719]], [[0.02456743]...   
1  [[[0.97475284]], [[0.9937784]], [[0.37172255]]...   
2  [[[0.9680168]], [[0.0082058655]], [[0.29154035...   
3  [[[0.9572456]], [[0.99069935]], [[0.05033453]]...   
4  [[[0.184256]], [[0.0006398597]], [[0.014315954...   

                                       preresnet_u67  \
0  [[[0.9008]], [[0.04977778]], [[0.06152666]], [...   
1  [[[0.7416709]], [[0.99948597]], [[0.072097324]...   
2  [[[0.9560007]], [[0.0061894692]], [[0.3604504]...   
3  [[[0.31696457]], [[0.99046564]], [[0.003620990...   
4  [[[0.037844375]], [[0.00064213324]], [[0.00495...   

                                      preresnet_u101  \
0  [[[0.9928462]], [[0.0033091686]], [[0.02205755...   
1  [[[0.8883914]], [[0.99836713]], [[0.21986316]]...   
2  [[[0.93580484]], [[0.037184846]], [[0.48354197...   
3  [[[0.90816665]], [[0.998226]], [[0.04174795]],...   
4  [[[0.6757472]], [[0.0011689868]], [[0.01058629...   

                                          resnet_w65  \
0  [[[0.9949687]], [[0.008769571]], [[0.05128505]...   
1  [[[0.9355388]], [[0.99766314]], [[0.25203508]]...   
2  [[[0.89877224]], [[0.007357184]], [[0.47415993...   
3  [[[0.9247875]], [[0.9722527]], [[0.03123361]],...   
4  [[[0.12146013]], [[0.000605252]], [[0.04767052...   

                                      se_resnext_u29  cluster4  
0  [[[0.99430543]], [[0.016006052]], [[0.02002830...         0  
1  [[[0.7101919]], [[0.969549]], [[0.27546024]], ...         1  
2  [[[0.9792124]], [[0.017325625]], [[0.5496751]]...         1  
3  [[[0.846639]], [[0.99171513]], [[0.06439011]],...         0  
4  [[[0.5738917]], [[0.0033817638]], [[0.01807783...         3

In [59]:
cluster4 = oof_folds.cluster4.values

In [60]:
y[:,0][np.where(cluster4 == 0)[0]]

array([1., 0., 1., ..., 1., 0., 0.], dtype=float32)

In [61]:
from sklearn.linear_model import Ridge

In [74]:
new_oof = np.zeros(train_five.shape[0])
for i in range(4):
    val_idx = np.where(cluster4 == i)[0]
    trn_idx = np.where(cluster4 != i)[0]
    train_x, val_x = train_five[trn_idx, :], train_five[val_idx, :]
    train_y, val_y = y[:,0][trn_idx], y[:,0][val_idx]
    clf = Ridge(alpha=0)
    clf.fit(train_x, train_y)
    oof_preds = clf.predict(val_x)
    new_oof[val_idx] = oof_preds
    


In [77]:
new_oof.max()

1.1424261331558228

In [67]:
val_x.shape

(10771, 140)

In [78]:
from sklearn.preprocessing import MinMaxScaler

In [81]:
scaler = MinMaxScaler()
new_oof = scaler.fit_transform(new_oof.reshape(-1,1))

In [85]:
new_oof.max()

0.9999999999999999

In [96]:
f1_score(y[:,0], (new_oof > 0.68)*1.)

0.8432444411612617

In [105]:
f1_score(y[:,0], (train_five[:,0] > 0.88)*1.)

0.8341106434611155

In [109]:
scores = [f1_score(y[:,0], (new_oof > th)*1.,) for th in threshold_0]

In [110]:
np.max(scores)

0.8432444411612617

In [116]:
scores = [f1_score(y[:,0], (train_five[:,4*28] > th)*1.,) for th in threshold_0]
np.max(scores)

0.8280603193376701

In [171]:
from tqdm import tqdm

In [175]:
all_columns = set(range(140))

all_good_features = []

for ii in tqdm(range(28)):
    print("Fitting feature", ii)
    first_five =  set(np.array(range(5))*(28)+ii)
    the_rest = np.array(list(all_columns - first_five))
    the_list = list(np.sort(list(first_five)))+list(the_rest)
    best_score = 0
    good_features = []
    for feature in the_list:
        new_oof = np.zeros(train_five.shape[0])
        temp_good_features = good_features+[feature]
        for i in range(4):
            val_idx = np.where(cluster4 == i)[0]
            trn_idx = np.where(cluster4 != i)[0]
            train_x, val_x = train_five[:,temp_good_features][trn_idx, :], train_five[:,temp_good_features][val_idx, :]
            train_y, val_y = y[:,ii][trn_idx], y[:,ii][val_idx]
            clf = Ridge(alpha=0)
            clf.fit(train_x, train_y)
            oof_preds = clf.predict(val_x)
            new_oof[val_idx] = oof_preds
            
        scaler = MinMaxScaler()
        new_oof = scaler.fit_transform(new_oof.reshape(-1,1))
        scores = [f1_score(y[:,ii], (new_oof > th)*1.,) for th in threshold_0]
        new_score = np.max(scores)
        if new_score > best_score:
            print(feature)
            print(new_score)
            best_score = new_score
            good_features.append(feature)
            
    all_good_features.append(good_features)
        

  0%|          | 0/28 [00:00<?, ?it/s]

Fitting feature 0
0
0.8360929557007989
28
0.8431079157694975
56
0.8455120290343098
84
0.8460111317254174
112
0.8487388724035607
2
0.8488757832657574
3
0.8488847926267281
6
0.8489006935222075
9
0.8489744724804485
13
0.8491433657197952
14
0.8493657309811754
16
0.849737095460268
38
0.8497685613775228
126
0.8503995264871264


  4%|▎         | 1/28 [02:13<1:00:11, 133.74s/it]

Fitting feature 1
1
0.834178696839641
29
0.8479485116653258
57
0.85192536720921
85
0.854376764824526
113
0.8623853211009175
0
0.8629032258064516
2
0.8629807692307693
4
0.8632921482662416
5
0.8642370845014018
63
0.8644953759549658
84
0.8648215002005616
101
0.8651685393258427
135
0.8655158570855078


  7%|▋         | 2/28 [04:01<54:38, 126.08s/it]  

Fitting feature 2
2
0.7938359017076219
30
0.8041087962962964
58
0.8085409252669039
86
0.8129256629473988
0
0.8130503825609933
3
0.815202034473015
4
0.8175473579262212
13
0.8176638176638177
16
0.8179359430604983
41
0.818220640569395
65
0.8183888414460575


 11%|█         | 3/28 [05:57<51:14, 122.98s/it]

Fitting feature 3
3
0.7400572701240852
31
0.7609536082474228
59
0.7619986850756082
87
0.768190598840953
0
0.7700291923451185
5
0.7736893520026049
11
0.7739413680781759
16
0.7745928338762215


 14%|█▍        | 4/28 [07:47<47:40, 119.17s/it]

Fitting feature 4
4
0.7757544224765869
32
0.7886133032694477
88
0.794928335170893
0
0.7970256127788489
2
0.7973568281938326
3
0.798129812981298
52
0.7983493810178817
98
0.7984602694528458
100
0.7988995873452543
117
0.7990088105726872
120
0.7992288625722942
126
0.7995594713656388
128
0.7998898981557941
138
0.8


 18%|█▊        | 5/28 [09:39<44:46, 116.81s/it]

Fitting feature 5
5
0.6931027209449484
33
0.7031736154324828
61
0.7075593952483802
89
0.7100742311770942
117
0.7107942973523422
0
0.7118012422360247
3
0.7122287568444534
6
0.7144967292677781
25
0.7154158648706436
29
0.7157219251336898
30
0.7162219398559931
31
0.7163543441226576
32
0.7167162909400254
34
0.7167409293443667
41
0.716893039049236
42
0.7169250371628796
45
0.7171974522292994
48
0.7173497557867913
69
0.717469751645086
73
0.7175896456609379
99
0.7179813401187447
101
0.7183725365543548
107
0.7185247986434931


 21%|██▏       | 6/28 [11:36<42:52, 116.91s/it]

Fitting feature 6
6
0.5623242736644798
34
0.6081447963800906
62
0.6190241498275012
90
0.6417221937467965
0
0.6418367346938775
18
0.6421643695763144
21
0.645758354755784
25
0.6483241620810406
27
0.6484063745019921
33
0.648729446935725
38
0.648782911077993
41
0.6494023904382471
45
0.650398406374502
71
0.650722471350274


 25%|██▌       | 7/28 [13:24<39:58, 114.21s/it]

Fitting feature 7
7
0.8000750891683875
35
0.8138288038454428
63
0.817743132887899
91
0.8235078725741486
119
0.8281392381993803
0
0.8288028802880287
1
0.8289260658391797
19
0.8291719058738998
21
0.8293037629521904
23
0.830492944841488
24
0.8307072187614509
25
0.8313470566991695
48
0.8314972006501715
58
0.8318584070796461
60
0.832309360318034
65
0.8324597867341407
78
0.8330321647994218
123
0.8332730560578662
132
0.8334839992768035


 29%|██▊       | 8/28 [15:20<38:14, 114.74s/it]

Fitting feature 8
8
0.9074074074074073
36
0.9215686274509803
120
0.9245283018867925
9
0.9320388349514563


 32%|███▏      | 9/28 [16:57<34:40, 109.51s/it]

Fitting feature 9
9
0.8409090909090908
37
0.8695652173913044
65
0.9111111111111111
93
0.9318181818181819


 36%|███▌      | 10/28 [18:34<31:43, 105.74s/it]

Fitting feature 10
10
0.8518518518518519
38
0.8928571428571429
66
0.9090909090909091
94
0.9259259259259259
122
0.9285714285714286


 39%|███▉      | 11/28 [20:12<29:15, 103.25s/it]

Fitting feature 11
11
0.7424872861766065
39
0.7754716981132076
67
0.7835337650323776
95
0.7907647907647908
25
0.7909441233140655
28
0.7911239749155812
30
0.7913253012048193
32
0.791907514450867
34
0.7919921875
35
0.7935420743639923
57
0.793743890518084
77
0.7941320293398532
79
0.7945205479452054
98
0.7947084762371387
109
0.7952987267384916
117
0.796078431372549


 43%|████▎     | 12/28 [22:00<27:55, 104.73s/it]

Fitting feature 12
12
0.6856368563685636
40
0.7211184694628403
96
0.7243735763097952
124
0.7416728349370836
0
0.7427724240177909
49
0.7430604982206407
56
0.743954480796586
61
0.7444839857651244
133
0.7446808510638298


 46%|████▋     | 13/28 [23:44<26:08, 104.55s/it]

Fitting feature 13
13
0.6941649899396379
41
0.7265388496468214
69
0.7294350842418236
97
0.7386831275720165
1
0.7399193548387096
4
0.7409700722394221
22
0.7414141414141415
47
0.7421638018200203
49
0.7436676798378927
61
0.7439024390243902


 50%|█████     | 14/28 [25:29<24:26, 104.73s/it]

Fitting feature 14
14
0.8389715832205684
42
0.8652214891611686
70
0.8735632183908045
98
0.8748241912798875
126
0.8750000000000001
0
0.8750589344648751
2
0.8754113775270334
3
0.8754716981132076
6
0.8759398496240601
11
0.8763516690173955
16
0.8794599807135969
18
0.8803088803088802
21
0.880539499036609
22
0.8810784785748677
31
0.8816169393647738


 54%|█████▎    | 15/28 [27:18<22:59, 106.10s/it]

Fitting feature 15
15
0.6666666666666666
43
0.6857142857142857


 57%|█████▋    | 16/28 [29:00<20:58, 104.90s/it]

Fitting feature 16
16
0.4134790528233151
44
0.45286686103012636
72
0.4653130287648054
100
0.47070506454816285
128
0.4918414918414919
0
0.49517684887459806
7
0.4951974386339381
12
0.495475113122172
14
0.49716231555051077
17
0.5072951739618407
18
0.5075268817204301
21
0.5097613882863341
22
0.5098468271334792
23
0.5104052573932093
24
0.5109649122807016
25
0.5113636363636364
30
0.5119453924914676
70
0.5125284738041002
99
0.5131578947368421
129
0.5153234960272418
136
0.5164212910532276


 61%|██████    | 17/28 [30:50<19:27, 106.17s/it]

Fitting feature 17
17
0.4043478260869565
45
0.4093023255813954
101
0.4137931034482759
129
0.4444444444444445
16
0.4454976303317536
70
0.4481132075471698


 64%|██████▍   | 18/28 [32:29<17:22, 104.22s/it]

Fitting feature 18
18
0.5225027442371021
46
0.563169164882227
74
0.5732416710735061
102
0.577424844015882
7
0.578420467185762
14
0.5789782736347622
16
0.5791009924109749
21
0.5795644891122279
24
0.5811777655476059
73
0.5825991189427313
89
0.5847176079734219
94
0.5853119823302043
96
0.585635359116022
124
0.58595909342178
135
0.5863586358635864


 68%|██████▊   | 19/28 [34:19<15:52, 105.81s/it]

Fitting feature 19
19
0.6118892001244943
47
0.6378056840713813
75
0.637848222862632
103
0.6514745308310992
6
0.6517229842756774
12
0.6519558676028084
21
0.6530748663101604
22
0.6535511837279092
23
0.6537691794529688
45
0.6542180726908969
51
0.6542305129913392


 71%|███████▏  | 20/28 [36:13<14:27, 108.43s/it]

Fitting feature 20
20
0.6072423398328691
48
0.6324786324786325
76
0.6488095238095237
104
0.6595174262734584
132
0.7191780821917808


 75%|███████▌  | 21/28 [37:52<12:19, 105.65s/it]

Fitting feature 21
21
0.6661354581673307
49
0.6830601092896176
77
0.6871367197371746
105
0.6951280763435459
133
0.6996582711049234
0
0.7006369426751592
6
0.7015787447054294
19
0.7016866228917215
25
0.7021526418786693
27
0.7023219410383511
28
0.7027664874786941
33
0.7028301886792453
52
0.7028938064685085
60
0.7029715931404634
67
0.7032190526040304
68
0.7032563025210085
72
0.7034175723451618
75
0.7036018336607728
88
0.7036308821601782
90
0.7045900353079639
102
0.7048987589810581
111
0.705067920585162


 79%|███████▊  | 22/28 [39:53<11:00, 110.01s/it]

Fitting feature 22
22
0.5974329054842473
50
0.643719806763285
106
0.6525934861278648
134
0.6649616368286445
0
0.6662395900064062
13
0.6674816625916871
16
0.6682956627978008
18
0.6687041564792177
21
0.6720197652872143
24
0.6724351050679852
27
0.6732550957381099
125
0.6736711990111248


 82%|████████▏ | 23/28 [41:38<09:03, 108.76s/it]

Fitting feature 23
23
0.8014718766427193
51
0.8092946058091286
79
0.8125105095005885
107
0.8151577503429357
135
0.8234289617486339
0
0.8236882065125697
1
0.8239891267414204
2
0.8241086587436334
4
0.8241702127659575
7
0.8253207869974337
12
0.8254347084896011
18
0.8255754475703325
19
0.8256786750896363
25
0.8259315977539562
28
0.8260721579305651
33
0.8264125255275698
44
0.8265531914893618


 86%|████████▌ | 24/28 [43:35<07:24, 111.15s/it]

Fitting feature 24
24
0.6807866868381242
52
0.7196110210696921
80
0.7308319738988582
108
0.7347611202635915
2
0.7368421052631579
25
0.7380560131795716


 89%|████████▉ | 25/28 [45:17<05:24, 108.25s/it]

Fitting feature 25
25
0.679745493107105
53
0.6934481630873215
81
0.698655590774948
137
0.7038508395571799
0
0.7054971011380717
1
0.7055019789285913
2
0.706048277732574
3
0.7062948739355486
7
0.7066354932086395
12
0.7069793103448275
14
0.7071304930481881
17
0.7071884540660561
19
0.7073130101615859
20
0.7076548133377644
26
0.7077907498877414
27
0.707903008531657
28
0.7079407806191117
33
0.7088677576293675
36
0.7090356452058579
43
0.7091461729759602
46
0.7091712707182319
54
0.7094493842160491
94
0.7094956637021488
95
0.7095454042694392
99
0.7095704096865152
104
0.7099055300812109
105
0.7099523967674083
110
0.7101986608378064
120
0.710390974948847
122
0.710408490409596
128
0.7104943049872829


 93%|█████████▎| 26/28 [47:28<03:50, 115.08s/it]

Fitting feature 26
26
0.528358208955224
54
0.5505443234836702
82
0.5609756097560976
110
0.5643994211287988
138
0.5863708399366085
4
0.5901116427432217


 96%|█████████▋| 27/28 [49:09<01:51, 111.00s/it]

Fitting feature 27
27
0.7200000000000001
55
0.8181818181818182


100%|██████████| 28/28 [50:45<00:00, 106.46s/it]


In [172]:
all_good_features.append(good_features)

In [177]:
len(all_good_features)

28

In [147]:
the_rest = np.array(list(all_columns - first_five))

In [144]:
train_five[:,list(first_five)].shape

(31072, 5)

In [146]:
train_five[:,[0,4,5]].shape

(31072, 3)

In [150]:
list(first_five)[::-1]

[27, 55, 83, 111, 139]

In [152]:
the_list = list(first_five)[::-1]+list(the_rest)

In [169]:
scores = [f1_score(y[:,0], (train_five[:,4*28] > th)*1.,) for th in threshold_0]
best_score = np.max(scores)
best_score

0.8280603193376701

In [178]:
all_good_features_array = np.array(all_good_features)

In [179]:
all_good_features_array

array([list([0, 28, 56, 84, 112, 2, 3, 6, 9, 13, 14, 16, 38, 126]),
       list([1, 29, 57, 85, 113, 0, 2, 4, 5, 63, 84, 101, 135]),
       list([2, 30, 58, 86, 0, 3, 4, 13, 16, 41, 65]),
       list([3, 31, 59, 87, 0, 5, 11, 16]),
       list([4, 32, 88, 0, 2, 3, 52, 98, 100, 117, 120, 126, 128, 138]),
       list([5, 33, 61, 89, 117, 0, 3, 6, 25, 29, 30, 31, 32, 34, 41, 42, 45, 48, 69, 73, 99, 101, 107]),
       list([6, 34, 62, 90, 0, 18, 21, 25, 27, 33, 38, 41, 45, 71]),
       list([7, 35, 63, 91, 119, 0, 1, 19, 21, 23, 24, 25, 48, 58, 60, 65, 78, 123, 132]),
       list([8, 36, 120, 9]), list([9, 37, 65, 93]),
       list([10, 38, 66, 94, 122]),
       list([11, 39, 67, 95, 25, 28, 30, 32, 34, 35, 57, 77, 79, 98, 109, 117]),
       list([12, 40, 96, 124, 0, 49, 56, 61, 133]),
       list([13, 41, 69, 97, 1, 4, 22, 47, 49, 61]),
       list([14, 42, 70, 98, 126, 0, 2, 3, 6, 11, 16, 18, 21, 22, 31]),
       list([15, 43]),
       list([16, 44, 72, 100, 128, 0, 7, 12, 14, 17, 18, 21

In [180]:
np.save('all_good_features', all_good_features)

In [181]:
all_good_features_2 = np.load('all_good_features.npy')

In [182]:
all_good_features_2

array([list([0, 28, 56, 84, 112, 2, 3, 6, 9, 13, 14, 16, 38, 126]),
       list([1, 29, 57, 85, 113, 0, 2, 4, 5, 63, 84, 101, 135]),
       list([2, 30, 58, 86, 0, 3, 4, 13, 16, 41, 65]),
       list([3, 31, 59, 87, 0, 5, 11, 16]),
       list([4, 32, 88, 0, 2, 3, 52, 98, 100, 117, 120, 126, 128, 138]),
       list([5, 33, 61, 89, 117, 0, 3, 6, 25, 29, 30, 31, 32, 34, 41, 42, 45, 48, 69, 73, 99, 101, 107]),
       list([6, 34, 62, 90, 0, 18, 21, 25, 27, 33, 38, 41, 45, 71]),
       list([7, 35, 63, 91, 119, 0, 1, 19, 21, 23, 24, 25, 48, 58, 60, 65, 78, 123, 132]),
       list([8, 36, 120, 9]), list([9, 37, 65, 93]),
       list([10, 38, 66, 94, 122]),
       list([11, 39, 67, 95, 25, 28, 30, 32, 34, 35, 57, 77, 79, 98, 109, 117]),
       list([12, 40, 96, 124, 0, 49, 56, 61, 133]),
       list([13, 41, 69, 97, 1, 4, 22, 47, 49, 61]),
       list([14, 42, 70, 98, 126, 0, 2, 3, 6, 11, 16, 18, 21, 22, 31]),
       list([15, 43]),
       list([16, 44, 72, 100, 128, 0, 7, 12, 14, 17, 18, 21