In [1]:
prefix = 'preresnet'
midx = '0'

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import f1_score, confusion_matrix

In [3]:
new = pd.read_csv('leak2d.csv')
new = new[new.Questionable != 1]
new.reset_index(inplace=True)
print(new.head())
print(new.shape)

ens = pd.read_csv('sub/'+prefix+midx+'.csv').fillna('')
ens = ens.set_index('Id')
print(ens.head())
print(ens.shape)

   index                                    Id Target  Questionable
0      0  94205e64-baca-11e8-b2b8-ac1f6b6435d0     16             0
1      1  53f49b94-bad3-11e8-b2b8-ac1f6b6435d0   9 10             0
2      3  47c3e666-bac6-11e8-b2b7-ac1f6b6435d0  14 25             0
3      4  05d45be8-bace-11e8-b2b8-ac1f6b6435d0   2 25             0
4      6  e5382de2-bad2-11e8-b2b8-ac1f6b6435d0   0 25             0
(272, 4)
                                     Predicted
Id                                            
00008af0-bad0-11e8-b2b8-ac1f6b6435d0         2
0000a892-bacf-11e8-b2b8-ac1f6b6435d0         5
0006faa6-bac7-11e8-b2b7-ac1f6b6435d0    0 5 25
0008baca-bad7-11e8-b2b9-ac1f6b6435d0         0
000cce7e-bad4-11e8-b2b8-ac1f6b6435d0          
(11702, 1)


In [4]:
# # create onehot matrix for a submission file
# def onehot_sub(csv0, num_classes=28):
#     c0 = pd.read_csv(csv0)
#     s0 = [s if isinstance(s,str) else '' for s in c0.Predicted]
#     p0 = [s.split() for s in s0]
#     y0 = np.zeros((c0.shape[0],num_classes)).astype(int)
#     # print(p0[:5])
#     for i in range(c0.shape[0]):
#         for j in p0[i]: y0[i,int(j)] = 1
#     # print(y0[:5])
    
#     y = pd.DataFrame(y0)
#     y.columns = ['y_'+str(i) for i in range(num_classes)]
    
#     c0 = pd.concat((c0,y),axis=1)
    
#     fname = csv0[:-4] + '_onehot.csv'
#     c0.to_csv(fname)      
#     print(fname)
    
# new['Predicted'] = new['Target'].values
# fname = 'sub/leak2dd.csv'
# new.to_csv(fname)
# onehot_sub(fname)

In [5]:
changed = 0
unchanged = 0
for i, item in enumerate(new['Id']):
#     print(test_preds.loc[i]['Target'])
    if ens.loc[item]['Predicted'] != new.loc[i]['Target']:
        print(ens.loc[item]['Predicted'],' => ', new.loc[i]['Target'])
        changed += 1
        ens.loc[item]['Predicted'] = new.loc[i]['Target']
    else:
        unchanged += 1

print('changed',changed,' unchanged',unchanged)

print()
fname = 'sub/'+prefix+midx+'d.csv'
ens.to_csv(fname)
print(fname)

0  =>  16
14  =>  14 25
0 3 25  =>  2 25
0 21 25  =>  0 25
0 5  =>  0 19 21
22  =>  0 22 23
0 25  =>  21 25
0 12 25  =>  12
12 21 26  =>  12 21 25
4 5 25  =>  7 21
0 21  =>  0 21 25
11 12  =>  12
4  =>  4 23
0 21 25  =>  21
18 25  =>  0 18 25
23 25  =>  2 23
0 21 25  =>  0 21 23
14 25  =>  0 14
14 16  =>  14
0 16  =>  0
0 12 16  =>  21
16 25  =>  14 16 25
2 25  =>  2 6 25
2  =>  1 2
12 21  =>  13 21
25  =>  0 25
16 25  =>  14 16 25
7 21 25  =>  0 21 22
16 25  =>  25
6 25  =>  2 6 14 25
0 19  =>  13
0 5 25  =>  13
7 25  =>  21 25
25  =>  14 25
0 22  =>  2 22
4  =>  4 21
4  =>  4 21
7  =>  2
0 17  =>  0 16 17 18
0 16  =>  0 16 17 18
0 2 11  =>  2 11
18 19  =>  0 19
18  =>  0 19
18  =>  0 19
12  =>  12 21 25
14 16  =>  0 14
14 16  =>  0 14
1  =>  1 5
4  =>  0
0 12  =>  21
0 16  =>  0
12 13 21  =>  13 21
0 14  =>  14 25
0 14  =>  14
0 14 16  =>  14
21 22 25  =>  25
16  =>  16 19 21 25
1 4 26  =>  1 4
5 16  =>  16
14 16  =>  14 16 17
5  =>  0 5 25
1 18  =>  1
14 16 25  =>  25
7 23  =>  7 25

In [6]:
name_label_dict = {
    0:  "Nucleoplasm",  
    1:  "Nuclear membrane",   
    2:  "Nucleoli",   
    3:  "Nucleoli fibrillar center",   
    4:  "Nuclear speckles",
    5:  "Nuclear bodies",   
    6:  "Endoplasmic reticulum",   
    7:  "Golgi apparatus",   
    8:  "Peroxisomes",   
    9:  "Endosomes",   
    10:  "Lysosomes",   
    11:  "Intermediate filaments",   
    12:  "Actin filaments",   
    13:  "Focal adhesion sites",   
    14:  "Microtubules",   
    15:  "Microtubule ends",   
    16:  "Cytokinetic bridge",   
    17:  "Mitotic spindle",   
    18:  "Microtubule organizing center",   
    19:  "Centrosome",   
    20:  "Lipid droplets",   
    21:  "Plasma membrane",   
    22:  "Cell junctions",   
    23:  "Mitochondria",   
    24:  "Aggresome",   
    25:  "Cytosol",   
    26:  "Cytoplasmic bodies",   
    27:  "Rods & rings"
}
LABEL_MAP = name_label_dict
np.set_printoptions(precision=3, suppress=True, linewidth=100)

In [7]:
# compute f1 score between two submission files
def f1_sub(csv0, csv1, num_classes=28):
    c0 = pd.read_csv(csv0)
    c1 = pd.read_csv(csv1)
    assert c0.shape == c1.shape
    s0 = [s if isinstance(s,str) else '' for s in c0.Predicted]
    s1 = [s if isinstance(s,str) else '' for s in c1.Predicted]
    p0 = [s.split() for s in s0]
    p1 = [s.split() for s in s1]
    y0 = np.zeros((c0.shape[0],num_classes)).astype(int)
    y1 = np.zeros((c0.shape[0],num_classes)).astype(int)
    # print(p0[:5])
    for i in range(c0.shape[0]):
        for j in p0[i]: y0[i,int(j)] = 1
        for j in p1[i]: y1[i,int(j)] = 1
    # print(y0[:5])
            
    return f1_score(y0, y1, average='macro')


# computute confusion matrices between two submission files
def f1_confusion(csv0, csv1, num_classes=28):
    c0 = pd.read_csv(csv0)
    c1 = pd.read_csv(csv1)
    assert c0.shape == c1.shape
    s0 = [s if isinstance(s,str) else '' for s in c0.Predicted]
    s1 = [s if isinstance(s,str) else '' for s in c1.Predicted]
    p0 = [s.split() for s in s0]
    p1 = [s.split() for s in s1]
    y0 = np.zeros((c0.shape[0],num_classes)).astype(int)
    y1 = np.zeros((c0.shape[0],num_classes)).astype(int)
    # print(p0[:5])
    for i in range(c0.shape[0]):
        for j in p0[i]: y0[i,int(j)] = 1
        for j in p1[i]: y1[i,int(j)] = 1
    # print(y0[:5])
    
    y0avg = np.average(y0,axis=0)
    y1avg = np.average(y1,axis=0)
    cm = [confusion_matrix(y0[:,i], y1[:,i]) for i in range(y0.shape[1])]
    fm = [f1_score(y0[:,i], y1[:,i]) for i in range(y0.shape[1])]
    for i in range(y0.shape[1]):
        print(LABEL_MAP[i])
        print(cm[i],' %4.2f' % fm[i],' %6.4f' % y0avg[i],' %6.4f' % y1avg[i],
             ' %6.4f' % (y0avg[i] - y1avg[i]))
        print()
#     print('y0avg')
#     print(y0avg)
#     print('y1avg')
#     print(y1avg)
#     print('y0avg - y1avg')
#     print(y0avg-y1avg)
    print('f1 macro')
    print(np.mean(fm))       
    return f1_score(y0, y1, average='macro')
 

In [8]:
f1_sub(fname,'sub/'+prefix+midx+'.csv')

0.9861395355809461

In [10]:
f1_sub(fname,'sub/ens43c.csv')

0.7331312014653518

In [11]:
f1_sub(fname,'sub/ens45c.csv')

0.7545422203332218

In [12]:
f1_sub(fname,'sub/ens53c.csv')

0.8022562170289441

In [13]:
f1_sub(fname,'sub/ens53d.csv')

0.8028110140665697

In [14]:
f1_sub(fname,'sub/ens55d.csv')

0.8042077295989284

In [15]:
f1_sub(fname,'sub/ens56d.csv')

0.808935617206798

In [16]:
f1_sub(fname,'sub/ens58d.csv')

0.8123168065617786

In [17]:
f1_sub(fname,'sub/ens59d.csv')

0.8199523488856206

In [19]:
f1_sub(fname,'sub/resnet15c.csv')

0.7891540012272731

In [20]:
f1_sub(fname,'sub/se_resnext11d.csv')

0.7723570778860426

In [23]:
f1_confusion(fname,'sub/'+prefix+midx+'.csv')

Nucleoplasm
[[7433   33]
 [  28 4208]]  0.99  0.3620  0.3624  -0.0004

Nuclear membrane
[[11185     2]
 [    3   512]]  1.00  0.0440  0.0439  0.0001

Nucleoli
[[10810     3]
 [   11   878]]  0.99  0.0760  0.0753  0.0007

Nucleoli fibrillar center
[[11005     9]
 [    2   686]]  0.99  0.0588  0.0594  -0.0006

Nuclear speckles
[[10819    13]
 [    2   868]]  0.99  0.0743  0.0753  -0.0009

Nuclear bodies
[[10820    12]
 [    1   869]]  0.99  0.0743  0.0753  -0.0009

Endoplasmic reticulum
[[11185     4]
 [    3   510]]  0.99  0.0438  0.0439  -0.0001

Golgi apparatus
[[10813     6]
 [    8   875]]  0.99  0.0755  0.0753  0.0002

Peroxisomes
[[11680     0]
 [    0    22]]  1.00  0.0019  0.0019  0.0000

Endosomes
[[11685     0]
 [    0    17]]  1.00  0.0015  0.0015  0.0000

Lysosomes
[[11691     0]
 [    0    11]]  1.00  0.0009  0.0009  0.0000

Intermediate filaments
[[11186     1]
 [    2   513]]  1.00  0.0440  0.0439  0.0001

Actin filaments
[[11187    10]
 [    1   504]]  0.99  0.0432  0.04

0.9861395355809461